platform :ios, ‘8.0’

target 'NewsDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NewsDemo

pod ‘AFNetworking’
pod ’SDWebImage’
pod ‘FMDB’
pod ‘Masonry’
pod ‘YYModel’
end
